name: Refresh Latest Development MSVC

on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: write

jobs:
  msvc:
    name: Build MSVC
    if: github.event.head_commit.message == 'ci-refresh-pre-msvc'
    uses: ./.github/workflows/windows-msvc.yml
    with:
      ref: ${{ github.sha }}
      pkg_version: 0.8.136-4-g7186356fcd

  replace:
    name: Replace development MSVC assets
    needs: msvc
    if: github.event.head_commit.message == 'ci-refresh-pre-msvc' && needs.msvc.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download MSVC artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v4
        with:
          path: dist
          merge-multiple: true

      - name: Replace development MSVC assets
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          set -euo pipefail
          mv dist/xemu-msvc-debug.zip dist/xemu-0.8.136-4-g7186356fcd-msvc-debug.zip
          mv dist/xemu-msvc-profile.zip dist/xemu-0.8.136-4-g7186356fcd-msvc-profile.zip
          mv dist/xemu-msvc-release.zip dist/xemu-0.8.136-4-g7186356fcd-msvc-release.zip
          gh release upload pre-release \
            dist/xemu-0.8.136-4-g7186356fcd-msvc-debug.zip \
            dist/xemu-0.8.136-4-g7186356fcd-msvc-profile.zip \
            dist/xemu-0.8.136-4-g7186356fcd-msvc-release.zip \
            --clobber --repo "$GH_REPO"
